BEGIN;
ALTER TABLE domains ALTER COLUMN project_id SET NOT NULL;
ALTER TABLE domains ALTER COLUMN org_id DROP NOT NULL;
DROP INDEX IF EXISTS idx_domains_org;
ALTER TABLE domains DROP COLUMN IF EXISTS org_id;
COMMIT;
