BEGIN;

ALTER TABLE api_tokens
  ADD COLUMN IF NOT EXISTS rate_limit_rpm  INT      NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ip_allowlist    TEXT     NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS request_count  BIGINT   NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_count_reset TIMESTAMPTZ NOT NULL DEFAULT now();

COMMIT;
